[package]
name = "spk_tracker"
version = "0.1.0"
edition = "2024"

[dependencies]
bdk_bitcoind_rpc = { version = "0.21" }
bdk_chain = { version = "0.23", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
anyhow = "1"
